### ISSUE TITLE
Regression bug with do-blocks

### ISSUE THREAD

**Issue by gentoid** [samu/blocky#11]
Just found that my patches had introduced regression bug with `do`-blocks, if they have parameters. The reason found as well - it's because `ruby-language` parses such cases as "do " (<- note space right after the keyword). Trying to figure out "what is what" - should it be fixed on the "parser" side, or on `blocky` side. I have opened ticket in the "parser" repo - see https://github.com/atom/language-ruby/issues/148

**Comment by samu** [comment]
@gentoid thanks for your investigations. I think we should fix this in the blocky package, as the atom repos usually take quite some time to introduce bug fixes.

I think we should be able to fix it by adjusting the regex on [this line](https://github.com/samu/blocky/blob/master/lib/blockmap-compiler.coffee#L1) to include whitespaces before and after the keywords.

**Comment by gentoid** [comment]
> I think we should fix this in the blocky package, as the atom core repos usually take quite some time to introduce bug fixes

yeah, I tend to think so as well.

Today/tomorrow I'm going to check corner & special cases carefully, and then will prepare new PR
