### ISSUE TITLE
problem when block has parametrs 

### ISSUE THREAD

**Issue by vtm9** [samu/blocky#14]
![bug](https://cloud.githubusercontent.com/assets/16337910/16341895/08badac6-3a38-11e6-9272-57a33b2dd0c2.png)

**Comment by gentoid** [comment]
@vtm9 I can assume that you have not updated blocky, it was fixed yesterday (see #12). I have `0.8.0` version and it looks fine:
![correct-do-block](https://cloud.githubusercontent.com/assets/232243/16342360/c0b3833a-3a42-11e6-8118-945ff0424c90.png)

**Comment by vtm9** [comment]
@gentoid Thank you! It's work

**Comment by gentoid** [comment]
@vtm9 if all works as expected, close the issue, please. Thanks
