### ISSUE TITLE
if else not working as expected

### ISSUE THREAD

**Issue by jonyeezs** [samu/blocky#5]
Here's a screen shot of what i mean.
![ifelse](https://cloud.githubusercontent.com/assets/10862726/14413465/432a8882-ffbe-11e5-88ae-6959f222563c.gif)

I don't think i have any conflicting packages.

Here's a [link to my package list](http://pastebin.com/PaPqRXGe).

**Comment by samu** [comment]
Thanks for reporting!

**Comment by samu** [comment]
I assume you are using hard instead of soft tabs. I attempted to fix it in `0.5.0`, let me know if it works.
